---
# tasks file for ansible-role-traefik
# - name: check if traefik config file exists
#   stat:
#     path: /etc/traefik.toml
#   register: traefik_config_file

# - name: Ensuere traefik file
#   template:
#     src: traefik.toml.j2
#     dest: /etc/traefik.toml

- name: Create Directory
  file:
    path: /var/local/traefik
    state: directory

- name: Upload docker compose
  template:
    src: docker-compose.yml.j2
    dest: /var/local/traefik/docker-compose.yml

- name: Run docker compose
  docker_service:
    project_src: /var/local/traefik
    state: present

# - name: Run docker ps
#  command: docker ps
