---
# tasks file for ansible-role-traefik
# - name: check if traefik config file exists
#   stat:
#     path: /etc/traefik.toml
#   register: traefik_config_file

# - name: Ensuere traefik file
#   template:
#     src: traefik.toml.j2
#     dest: /etc/traefik.toml

- name: Install packages
  apt:
    name: [python-pip]
    state: present

- name: Install pip packages
  pip:
    name: ["jsondiff", "python-consul"]
    state: present

- name: Create network for traefik
  docker_network:
    name: traefik-net
    driver: overlay
  when: inventory_hostname == groups['docker_swarm_manager'][0]

- name: Create Directory
  file:
    path: /var/local/traefik
    state: directory

- name: Upload docker compose
  template:
    src: docker-compose.yml.j2
    dest: /var/local/traefik/docker-compose.yml

- name: Upload traefik config
  template:
    src: traefik.toml.j2
    dest: /var/local/traefik/traefik.toml

- name: Run docker compose
  docker_stack:
    state: present
    name: traefik
    compose:
      - /var/local/traefik/docker-compose.yml
  when: inventory_hostname == groups['docker_swarm_manager'][0]

- name: Añadimos el servidor como un traefik exporter de prometheus
  consul:
    service_name: traefik
    service_port: 8080
